In [1]:
import torch

/home/taylor/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
P = torch.tensor(
	[[1, 3],
    [4, 1]]
)

In [12]:
P

tensor([[1, 3],
        [4, 1]])

In [7]:
P.sum(1)

tensor([4, 5])

In [8]:
P + P.sum(1)

tensor([[5, 8],
        [8, 6]])

In [14]:
P.sum(1, keepdim=True)

tensor([[4],
        [5]])

In [9]:
P + P.sum(1, keepdim=True)

tensor([[5, 7],
        [9, 6]])